### ISSUE TITLE
Lexer fails on floats/doubles

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#8]
It seems that something goes wrong when lexing (or parsing?) floating point numbers. On `examples/types.cco` we get:
`Syntax error, unexpected token LITERAL_INT( -4 ), line 7, column 11.`
and the number is `3e-4`.
Similarly, `3.14` doesn't work either.

**Comment by rafalcieslak** [comment]
I can't reproduce this:

```
$ ./CCoscope -o types ../examples/types.cco 
Parsing ../examples/types.cco
Found 0 prototypes and 1 function definitions. 
creating 3.14159
Writing out IR for module ../examples/types.cco to /tmp/fileKr8MIy.ll
Executing: '/usr/bin/llc-3.6 /tmp/fileKr8MIy.ll -o /tmp/filewLwzDg.s'...
Executing: '/usr/bin/clang-3.6 -c /tmp/filewLwzDg.s -o /tmp/fileCGsoAY.o'...
Executing: '/usr/bin/clang-3.6 /tmp/fileCGsoAY.o   -o types'...
$ ./types 
10
3.141590
1
0
$
```

Either this has been fixed, or I am missing something.

**Comment by socumbersome** [comment]
Aww, I forgot to mention in which commit that problem appeared.
So, `3.14` has been fixed somewhere :), but `3e-4` still fails. Can you confirm this?

**Comment by rafalcieslak** [comment]
You are right. Apparently the `3` in `3e-4` is interpreted as an int, because `e` classifies as a possible character that ends a literal value - while it should not.
